const images = [
  {
    id: '1',
    url: '181006.jpg',
    category: 'tue',
    title: 'Wave',
  },
  {
    id: '2',
    url: '181007.jpg',
    category: 'tue',
    title: 'Aurora',
  },
  {
    id: '3',
    url: '181008.jpg',
    category: 'tue',
    title: 'Wedding 2',
  },
  {
    id: '4',
    url: '181009.jpg',
    category: 'tue',
    title: 'Beach and Sea from drone',
  },
  {
    id: '5',
    url: '181109.jpg',
    category: 'tue',
    title: 'Mountain',
  },
  {
    id: '6',
    url: '181110.jpg',
    category: 'tue',
    title: 'Road from Drone',
  },
  {
    id: '7',
    url: '181111.jpg',
    category: 'tue',
    title: 'Portrait 1',
  },
  {
    id: '8',
    url: '181112.jpg',
    category: 'tue',
    title: 'Wedding 1',
  },
  {
    id: '9',
    url: '181114.jpg',
    category: 'tue',
    title: 'Hills',
  },
  {
    id: '11',
    url: '181115.jpg',
    category: 'tue',
    title: 'Portrait 2',
  },
  {
    id: '12',
    url: '181116.jpg',
    category: 'tue',
    title: 'Lake',
  },
  {
    id: '13',
    url: '181117.jpg',
    category: 'tue',
    title: 'Landscape lake',
  },
  {
    id: '14',
    url: '181111.jpg',
    category: 'landscape',
    title: 'Mountain Snowy',
  },
  {
    id: '15',
    url: 'aurora2.jpg',
    category: 'landscape',
    title: 'Aurora2',
  },
  {
    id: '16',
    url: 'greenMountain.jpg',
    category: 'landscape',
    title: 'Mountain Green',
  },
  {
    id: '17',
    url: 'portrait3.jpg',
    category: 'portrait',
    title: 'Portrait 3',
  },
  {
    id: '18',
    url: 'portrait4.jpg',
    category: 'portrait',
    title: 'Portrait 4',
  },
  {
    id: '19',
    url: 'portrait5.jpg',
    category: 'portrait',
    title: 'Portrait 5',
  },
  {
    id: '20',
    url: 'portrait6.jpg',
    category: 'portrait',
    title: 'Portrait 6',
  },
  {
    id: '21',
    url: 'portrait7.jpg',
    category: 'portrait',
    title: 'Portrait 7',
  },
  {
    id: '22',
    url: 'wedding3.jpg',
    category: 'wedding',
    title: 'Wedding ',
  },
  {
    id: '23',
    url: 'wedding4.jpg',
    category: 'wedding',
    title: 'Wedding ',
  },
  {
    id: '24',
    url: 'wedding5.jpg',
    category: 'wedding',
    title: 'Wedding ',
  },
  {
    id: '25',
    url: 'wedding6.jpg',
    category: 'wedding',
    title: 'Wedding ',
  },
  {
    id: '26',
    url: 'drone1.jpg',
    category: 'drone',
    title: 'Drone 1',
  },
  {
    id: '27',
    url: 'drone2.jpg',
    category: 'drone',
    title: 'Drone 2',
  },
  {
    id: '28',
    url: 'drone3.jpg',
    category: 'drone',
    title: 'Drone 3',
  },
  {
    id: '29',
    url: 'drone4.jpg',
    category: 'drone',
    title: 'Drone 4',
  },
  {
    id: '30',
    url: 'drone5.jpg',
    category: 'drone',
    title: 'Drone 5',
  },    
];
