const images = [
  /* Tuesday */
  {
    id: '1',
    url: '181006.jpg',
    category: 'tue',
    title: 'Wave',
  },
  {
    id: '2',
    url: '181007.jpg',
    category: 'tue',
    title: 'Aurora',
  },
  {
    id: '3',
    url: '181008.jpg',
    category: 'tue',
    title: 'Wedding 2',
  },
  {
    id: '4',
    url: '181009.jpg',
    category: 'tue',
    title: 'Beach and Sea from drone',
  },
  {
    id: '5',
    url: '181109.jpg',
    category: 'tue',
    title: 'Mountain',
  },
  {
    id: '6',
    url: '181110.jpg',
    category: 'tue',
    title: 'Road from Drone',
  },
  {
    id: '7',
    url: '181111.jpg',
    category: 'tue',
    title: 'Portrait 1',
  },
  {
    id: '8',
    url: '181112.jpg',
    category: 'tue',
    title: 'Wedding 1',
  },
  {
    id: '9',
    url: '181114.jpg',
    category: 'tue',
    title: 'Hills',
  },
  {
    id: '10',
    url: '181115.jpg',
    category: 'tue',
    title: 'Portrait 2',
  },
  {
    id: '11',
    url: '181116.jpg',
    category: 'tue',
    title: 'Lake',
  },
  {
    id: '12',
    url: '181117.jpg',
    category: 'tue',
    title: 'Landscape lake',
  },
  /* Wednesday */  
  {
    id: '13',
    url: '181328.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '14',
    url: '181329.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '15',
    url: '181330.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '16',
    url: '181331.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '17',
    url: '181332.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '18',
    url: '181333.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  /* Wednesday 2 */
  {
    id: '19',
    url: '181373.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '20',
    url: '181374.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '21',
    url: '181375.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '22',
    url: '181376.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '23',
    url: '181377.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '24',
    url: '181378.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '25',
    url: '181379.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '26',
    url: '181380.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  /* Wed Dinner */
  {
    id: '27',
    url: '181400.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '28',
    url: '181401.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  {
    id: '29',
    url: '181402.jpg',
    category: 'wed',
    title: 'Mountain Snowy',
  },
  /* Thu */
  {
    id: '30',
    url: '140.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '31',
    url: '141.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '32',
    url: '142.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '33',
    url: '143.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '34',
    url: '150.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '35',
    url: '151.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '36',
    url: '152.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '37',
    url: '153.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '38',
    url: '154.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '39',
    url: '155.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '40',
    url: '156.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '41',
    url: '157.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '42',
    url: '158.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '43',
    url: '160.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '44',
    url: '162.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '45',
    url: '163.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
  {
    id: '46',
    url: '164.jpg',
    category: 'thu',
    title: 'Mountain Snowy',
  },
    /* Fri */
  {
    id: '47',
    url: '167.jpg',
    category: 'fri',
    title: 'Mountain Snowy',
  },
  {
    id: '48',
    url: '168.jpg',
    category: 'fri',
    title: 'Mountain Snowy',
  },
  {
    id: '49',
    url: '169.jpg',
    category: 'fri',
    title: 'Mountain Snowy',
  },
  {
    id: '50',
    url: '172.jpg',
    category: 'fri',
    title: 'Mountain Snowy',
  },
  {
    id: '51',
    url: '173.jpg',
    category: 'fri',
    title: 'Mountain Snowy',
  },
  {
    id: '52',
    url: '174.jpg',
    category: 'fri',
    title: 'Mountain Snowy',
  },
  {
    id: '53',
    url: '175.jpg',
    category: 'fri',
    title: 'Mountain Snowy',
  },
  {
    id: '54',
    url: '178.jpg',
    category: 'fri',
    title: 'Mountain Snowy',
  },
  {
    id: '55',
    url: '179.jpg',
    category: 'fri',
    title: 'Mountain Snowy',
  },
  {
    id: '56',
    url: '180.jpg',
    category: 'fri',
    title: 'Mountain Snowy',
  },
  {
    id: '57',
    url: '181.jpg',
    category: 'fri',
    title: 'Mountain Snowy',
  },
  /* Sat */
  {
    id: '58',
    url: '187.jpg',
    category: 'sat',
    title: 'Mountain Snowy',
  },
  {
    id: '59',
    url: '188.jpg',
    category: 'sat',
    title: 'Mountain Snowy',
  },
];